### ISSUE TITLE
AttributeError: protocols

### ISSUE THREAD

**Issue by lordlycastle** [paulhammond/webkit2png#89]
I'm getting this error when I run the command.
```
Traceback (most recent call last):
  File "/usr/local/bin/webkit2png", line 78, in <module>
    class WebkitLoad (Foundation.NSObject, WebKit.protocols.WebFrameLoadDelegate):
  File "/Library/Python/2.7/site-packages/objc/_lazyimport.py", line 163, in __getattr__
    raise AttributeError(name)
AttributeError: protocols
```
Any idea why this could be happening.

**Comment by codingisacopingstrategy** [comment]
Having the same, with the 0.7 version that is on Homebrew, under OS X 10.9.5

**Comment by igorbogdanov** [comment]
Due to the change of rules for mapping python into obj-c in 3.0+ versions of PyObjC this command line tool could not be used with 3.0+ PyObjC, generating Error described in in Issue 89. The issue is now fixed, but nu sure if it is backwards compatible so suggest having this fix as a separate branch. See pull #102

**Comment by paulhammond** [comment]
This is because you've installed a non-standard version of PyObjc, and I don't know if it's possible to fix it and maintain compatibility with the version that is installed by default on a Mac. You can use the code in PR #102 while we try to work this out.
